---
services:
  conan-exiles-enhanced:
    image: indifferentbroccoli/conan-exiles-enhanced-server-docker
    platform: linux/amd64
    restart: unless-stopped
    container_name: conan-exiles-enhanced
    stop_grace_period: 30s
    ports:
      - 7777:7777/udp
      - 7778:7778/udp
      - 27015:27015/udp
    env_file:
      - .env
    volumes:
      - ./server-files:/home/steam/server-files
